# db:
#   image: postgres
kanhub_redis:
  image: redis
  ports:
    - "6379:6379"
kanhub_db:
  image: postgres
  ports:
    - "5432:5432"
kanhub_app:
  build: .
  links:
    - kanhub_db
  ports:
    - "8080:8080"
  environment:
    - POSTGRES_HOST=kanhub_db
    - REDIS_HOST=kanhub_redis