# db:
#   image: postgres

version: "2.0"
services:
  kanhub_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=StageHehexd
      - POSTGRES_TRUST_LOCALNET=true
  kanhub_app:
    build: .
    links:
      - kanhub_db
    ports:
      - "8080:8080"
    environment:
      - PGHOST=kanhub_db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=StageHehexd